---
- hosts: all
  tasks:
    - name: install httpd
      package:
        name: httpd
        state: installed
    - name: configure
      shell: "echo Hello  !! > /var/www/html/index.html"
    - name: start service
      service:
        name: httpd
        state: started
    - name: add user
      user:
        name: nirmal
        state: present
